# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = 'omni-parser-app'
primary_region = 'ord'
swap_size_mb = 32768 # 32gb

[build]

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '32gb'
  cpu_kind = 'performance'
  cpus = 4
  gpu_kind = 'l40s'

[mounts]
  source = "data"
  destination = "/data"
  initial_size = "20gb" # optional - the size of the volume created on first deploy
