# fly.toml app configuration file generated for omniparser-api-calls on 2026-01-16T16:33:49-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'omniparser-api-calls'
primary_region = 'ord'
swap_size_mb = 2048

[build]

[[mounts]]
  source = 'data'
  destination = '/data'
  initial_size = '2gb'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'performance-2x'
  cpu_kind = 'performance'
  gpu_kind = 'a10'
  memory = '16gb'
  memory_mb = 16384
  cpus = 2
  gpus = 1
